In [ ]:
import numpy as np
import pandas as pd

## No 1

a) Buatlah sebuah array dengan perintah arrange yang nilai start dan end adalah sebuah input! b) Dari array yang terbentuk tersebut, buatlah versi 2 dan 3 dimensinya!

In [4]:
start=int(input('Mulai: '))
end=int(input('Selesai: '))

Mulai: 1
Selesai: 13


In [5]:
array_awal=np.arange(start,end)
array_awal

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
array_awal.reshape(2,-1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [7]:
array_awal.reshape(2,3,-1)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

## No 2

a) Buatlah sebuah array 1 dimensi dari data random integer sebanyak “n”, dimana “n” tersebut adalah sebuah input ! b) Batasan random juga ditentukan dalam input. c) Ubahlah array 1 dimensi tersebut ke dalam bentuk 2 dimensi atau matrix! d) Setelah diubah ke bentuk 2 dimensi, setiap barisnya baliklah urutan datanya! Misalnya dari 1, 2, 3 menjadi 3, 2, 1.

In [8]:
start=int(input('Mulai: '))
end=int(input('Selesai: '))
n=int(input('Jumlah data: '))

Mulai: 1
Selesai: 21
Jumlah data: 40


In [9]:
data=np.random.randint(start,end,n)
data

array([17, 10, 16,  2,  1,  7, 16,  5, 18,  7,  2,  4, 15,  9, 12, 16, 12,
       10, 19,  6, 18,  9,  7, 19, 17,  6, 15,  8,  8, 20,  7, 15, 11,  8,
       18,  5, 16,  7,  6, 13])

In [10]:
matrix=data.reshape(8,-5)
matrix

array([[17, 10, 16,  2,  1],
       [ 7, 16,  5, 18,  7],
       [ 2,  4, 15,  9, 12],
       [16, 12, 10, 19,  6],
       [18,  9,  7, 19, 17],
       [ 6, 15,  8,  8, 20],
       [ 7, 15, 11,  8, 18],
       [ 5, 16,  7,  6, 13]])

In [12]:
np.fliplr(matrix)

array([[ 1,  2, 16, 10, 17],
       [ 7, 18,  5, 16,  7],
       [12,  9, 15,  4,  2],
       [ 6, 19, 10, 12, 16],
       [17, 19,  7,  9, 18],
       [20,  8,  8, 15,  6],
       [18,  8, 11, 15,  7],
       [13,  6,  7, 16,  5]])

In [14]:
matrix[:,::-1]

array([[ 1,  2, 16, 10, 17],
       [ 7, 18,  5, 16,  7],
       [12,  9, 15,  4,  2],
       [ 6, 19, 10, 12, 16],
       [17, 19,  7,  9, 18],
       [20,  8,  8, 15,  6],
       [18,  8, 11, 15,  7],
       [13,  6,  7, 16,  5]])

## No 3

a) Buatlah sebuah array 2 dimensi dengan ukuran 10 x 10! b) Isi dari array tersebut adalah:

Sisi luarnya merupakan angka 4.
Selain sisi luar, angka yang ditampilkan adalah 0.

In [15]:
my_array=np.ones((10,10))*4
my_array[1:-1,1:-1]=0
my_array

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

## No 4

a) Buatlah sebuah Series dengan menggunakan library Pandas! b) Index pada Series tersebut berupa huruf lowercase dari a hingga z. c) Data dari tiap indexnya adalah nomor dari 1 hingga 26.

In [16]:
import string

In [17]:
lbls=list(string.ascii_lowercase) 
arys=np.arange(1,27)
pd.Series(arys,lbls)

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
k    11
l    12
m    13
n    14
o    15
p    16
q    17
r    18
s    19
t    20
u    21
v    22
w    23
x    24
y    25
z    26
dtype: int32

## No 5

a) Buatlah sebuah Series menggunakan angka random integer dari 1 hingga 5 sebanyak 100! b) Hitunglah banyaknya frekuensi tiap angka! c) Cari tahu 2 nilai dengan frekuensi tertinggi!

In [20]:
np1=np.random.randint (1,5,100)
np1

array([2, 3, 4, 3, 4, 3, 1, 1, 3, 2, 3, 4, 3, 2, 2, 1, 1, 1, 2, 3, 4, 4,
       4, 2, 4, 1, 2, 2, 3, 4, 2, 3, 1, 3, 4, 2, 1, 4, 4, 4, 1, 2, 2, 1,
       3, 3, 3, 4, 4, 3, 4, 3, 4, 3, 2, 3, 2, 2, 4, 3, 2, 1, 4, 4, 3, 3,
       4, 3, 2, 2, 1, 1, 1, 3, 1, 4, 4, 1, 3, 4, 2, 4, 2, 4, 2, 1, 3, 2,
       4, 3, 4, 2, 4, 3, 3, 4, 4, 2, 1, 1])

In [21]:
srs1=pd.Series(np1)
srs1

0     2
1     3
2     4
3     3
4     4
     ..
95    4
96    4
97    2
98    1
99    1
Length: 100, dtype: int32

In [22]:
srsfreq=srs1.value_counts()
srsfreq

4    30
3    27
2    24
1    19
dtype: int64

In [24]:
srsfreq.head(2)

4    30
3    27
dtype: int64

## No 6

a) Import library “seaborn”. Lalu, load data yang bernama “MPG”! b) Tampilkan 5 data teratas pada DataFrame dari data “MPG”! c) Tampilkan statistik deskriptif atau Describe data selain data numerik! d) Tampilkan seluruh nama kolom pada DataFrame! e) Hitung Jumlah Missing Value (data kosong) di setiap kolomnya!

In [29]:
import seaborn as sns
mpg=sns.load_dataset('mpg')
mpg

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  origin                       name  
0            70     usa  chevrolet chevelle malibu  
1            70     usa          buick skylark 320  
2            70     usa         plymouth satellite  
3            70     usa              amc rebel sst  
4            70     usa                ford torino  
..          ...     ...                        ...  
393          82     usa            ford mustang gl  
394          82  europe                  vw pickup  
395          82     usa              dodge rampage  
396          82     usa                ford ranger  
397          82     usa                 chevy s-10  

[398 rows x 9 columns]

In [30]:
mpg.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  
3          70    usa              amc rebel sst  
4          70    usa                ford torino

In [31]:
mpg.describe(include=object)

origin        name
count     398         398
unique      3         305
top       usa  ford pinto
freq      249           6

In [32]:
mpg.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [33]:
mpg.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

## No 7

a) Import library “seaborn”, lalu load data yang bernama “MPG”! b) Tampilkan Missing value (data kosong) pada kolom ‘horsepower’! c) Tampilkan index lokasi missing value tersebut!

In [34]:
mpg[mpg['horsepower'].isna()]

mpg  cylinders  displacement  horsepower  weight  acceleration  \
32   25.0          4          98.0         NaN    2046          19.0   
126  21.0          6         200.0         NaN    2875          17.0   
330  40.9          4          85.0         NaN    1835          17.3   
336  23.6          4         140.0         NaN    2905          14.3   
354  34.5          4         100.0         NaN    2320          15.8   
374  23.0          4         151.0         NaN    3035          20.5   

     model_year  origin                  name  
32           71     usa            ford pinto  
126          74     usa         ford maverick  
330          80  europe  renault lecar deluxe  
336          80     usa    ford mustang cobra  
354          81  europe           renault 18i  
374          82     usa        amc concord dl

In [36]:
mpg[mpg['horsepower'].isna()].index

Int64Index([32, 126, 330, 336, 354, 374], dtype='int64')

## No 8

a) Import library “seaborn”, lalu load data yang bernama “MPG”! b) Lakukan grouping atau pengelompokan berdasarkan kolom ‘origin’! Tampilkan rata-rata dari ‘horsepower’ di setiap kelompok origin-nya!

In [37]:
mpg.groupby('model_year').mean()['horsepower']

model_year
70    147.827586
71    107.037037
72    120.178571
73    130.475000
74     94.230769
75    101.066667
76    101.117647
77    105.071429
78     99.694444
79    101.206897
80     77.481481
81     81.035714
82     81.466667
Name: horsepower, dtype: float64

## No 9

a) Import library “seaborn”, lalu load data yang bernama “MPG”! b) Buatlah sebuah kolom baru yang bernama ‘horse_origin’! c) Kolom ‘horse_origin’ ini harus diisi menggunakan fungsi berisikan: ❑ Jika nilai ‘horsepower’ <= 105, tampilkan ‘lower’ + ‘nama origin’ pada baris yang sama. Contohnya ‘lower USA’. ❑ Jika nilai ‘horsepower’ > 105, tampilkan ‘upper’ + ‘nama origin’.

In [38]:
mpg['horsepower'].apply(lambda x: 'lower' if x<=105 else 'upper')+' '+mpg['origin']

0         upper usa
1         upper usa
2         upper usa
3         upper usa
4         upper usa
           ...     
393       lower usa
394    lower europe
395       lower usa
396       lower usa
397       lower usa
Length: 398, dtype: object

In [44]:
['lower ' if i<=105 else 'upper ' for i in mpg['horsepower']]+(mpg['origin'])

0         upper usa
1         upper usa
2         upper usa
3         upper usa
4         upper usa
           ...     
393       lower usa
394    lower europe
395       lower usa
396       lower usa
397       lower usa
Name: origin, Length: 398, dtype: object

In [45]:
np.where(mpg.horsepower<=105,'lower '+mpg.origin,'upper '+mpg.origin)

array(['upper usa', 'upper usa', 'upper usa', 'upper usa', 'upper usa',
       'upper usa', 'upper usa', 'upper usa', 'upper usa', 'upper usa',
       'upper usa', 'upper usa', 'upper usa', 'upper usa', 'lower japan',
       'lower usa', 'lower usa', 'lower usa', 'lower japan',
       'lower europe', 'lower europe', 'lower europe', 'lower europe',
       'upper europe', 'lower usa', 'upper usa', 'upper usa', 'upper usa',
       'upper usa', 'lower japan', 'lower usa', 'lower japan',
       'upper usa', 'lower usa', 'lower usa', 'lower usa', 'lower usa',
       'lower usa', 'upper usa', 'upper usa', 'upper usa', 'upper usa',
       'upper usa', 'upper usa', 'upper usa', 'upper usa', 'lower usa',
       'lower usa', 'lower usa', 'lower usa', 'lower europe',
       'lower europe', 'lower europe', 'lower japan', 'lower japan',
       'lower europe', 'lower usa', 'lower japan', 'lower usa',
       'lower europe', 'lower usa', 'lower usa', 'upper usa', 'upper usa',
       'upper usa', 'upper

In [49]:
def add_horse(x):
    if x['horsepower']<=105:
        return f'lower {x["origin"]}'
    else:
        return f'upper {x["origin"]}'

In [50]:
mpg[['horsepower','origin']].apply(add_horse,axis=1)

0         upper usa
1         upper usa
2         upper usa
3         upper usa
4         upper usa
           ...     
393       lower usa
394    lower europe
395       lower usa
396       lower usa
397       lower usa
Length: 398, dtype: object

## NO 10

a) Import library “seaborn”, lalu load data yang bernama “MPG”! b) Lakukan pengelompokan atau grouping kolom ‘weight’ berdasarkan kolom ‘origin’ dengan aggregating mean, standart deviasi, sum, count, min, dan max! c) Lakukan reset index sehingga kolom ‘origin’ tidak lagi menjadi index tapi tetap menjadi kolom!

In [51]:
mpg.groupby('origin')['weight'].agg(['mean','std','sum','count','min','max']).reset_index()

origin         mean         std     sum  count   min   max
0  europe  2423.300000  490.043191  169631     70  1825  3820
1   japan  2221.227848  320.497248  175477     79  1613  2930
2     usa  3361.931727  794.792506  837121    249  1800  5140